# Copyright (c) 2026, Gift Braimah and contributors
# For license information, please see license.txt

"""
Composite Item Utilities

This module handles stock deduction for composite items (recipe-based items).
When a composite item is sold, ingredients are automatically consumed from stock.
"""

import frappe
from frappe import _
from frappe.utils import flt, now
from erpnext.stock.doctype.stock_entry.stock_entry_utils import make_stock_entry


def process_composite_items_in_invoice(doc, method=None):
	"""
	Process composite items in POS Invoice or Sales Invoice.
	Creates Material Consumption stock entries for ingredients.
	
	Args:
		doc: POS Invoice or Sales Invoice document
		method: Event method (on_submit, on_cancel)
	"""
	if doc.get('fnb_version') == 'FNB v1':
		from hospitality_core.hospitality_core.api.fnb.pos import process_invoice
		if process_invoice(doc):
			return
	if is_consolidated_pos_sales_invoice(doc):
		return

	# Determine if this is a cancellation
	is_cancel = doc.docstatus == 2
	if is_cancel:
		# Hoàn chứng từ đã tạo, bất kể Item Master đã thay đổi sau lần bán.
		for item in doc.items:
			reverse_ingredient_consumption(doc, item)
		return
	
	# Get composite items from invoice
	composite_items = []
	for item in doc.items:
		item_flags = frappe.db.get_value("Item", item.item_code, ["is_composite_item", "is_stock_item"], as_dict=True)
		if not item_flags or not item_flags.is_composite_item:
			continue
		if item_flags.is_stock_item and not is_cancel:
			# TRƯỚC ĐÂY: không kiểm tra is_stock_item — 1 Item vừa
			# is_composite_item=1 vừa is_stock_item=1 (checkbox
			# "is_stock_item==0" trên form chỉ là gợi ý ẩn/hiện phía client,
			# KHÔNG chặn được ở server — bulk edit/Data Import/API vẫn có
			# thể tạo ra tổ hợp này) sẽ bị trừ kho HAI LẦN cho cùng 1 lần
			# bán: 1 lần chính nó, 1 lần nữa qua nguyên liệu composite ở đây
			# — âm thầm lệch tồn kho không ai phát hiện. Với Sales Invoice
			# thường, lần trừ "chính nó" đi qua Stock Ledger chuẩn của
			# ERPNext (update_stock=1 thật sự có tác dụng ở đó — xem
			# `stock.py`'s `disable_stock_for_consolidated_pos_sales_invoice`);
			# với POS Invoice, lần trừ "chính nó" đi qua
			# `stock.py`'s `deduct_stock_items_for_pos_invoice()` (Stock Entry
			# thủ công — ĐÃ xác minh trực tiếp mã nguồn ERPNext rằng
			# `POSInvoice.on_submit()`/`validate()` tự nhảy qua
			# `SalesInvoice`'s override bằng `super(SalesInvoice, self)`,
			# nên field `update_stock` không hề được core xử lý cho riêng
			# POS Invoice). Dù cơ chế trừ khác nhau giữa 2 doctype, kết quả
			# double-deduction nếu Item vừa composite vừa stock là như
			# nhau — chặn rõ ràng thay vì âm thầm trừ trùng.
			frappe.throw(_(
				"Item {0} được đánh dấu VỪA LÀ composite item VỪA LÀ stock item — sẽ bị trừ kho HAI LẦN mỗi "
				"lần bán (1 lần chính nó, 1 lần qua nguyên liệu composite). Composite item phải có Is Stock "
				"Item = 0. Vui lòng sửa Item Master trước khi xuất hóa đơn."
			).format(item.item_code))
		composite_items.append(item)

	if not composite_items:
		return

	# Process each composite item
	for item in composite_items:
		try:
			if is_cancel:
				# Reverse the stock entry
				reverse_ingredient_consumption(doc, item)
			else:
				# Create consumption entry
				create_ingredient_consumption_entry(
					item_code=item.item_code,
					qty=item.stock_qty,
					warehouse=item.warehouse,
					invoice_ref=doc.name,
					invoice_type=doc.doctype,
					invoice_item=item.name,
					company=doc.company,
					posting_date=doc.posting_date,
					posting_time=doc.posting_time
				)
		except Exception as e:
			frappe.log_error(
				message=f"Error processing composite item {item.item_code}: {str(e)}",
				title="Composite Item Processing Error"
			)
			# Re-raise to prevent invoice submission if stock deduction fails
			frappe.throw(_("Failed to process composite item {0}. Error: {1}").format(
				item.item_code, str(e)
			))


def is_consolidated_pos_sales_invoice(doc):
	"""
	Return true when a Sales Invoice was generated by POS Closing consolidation.
	Composite stock is already consumed when the original POS Invoice is submitted.
	"""
	if doc.doctype != "Sales Invoice":
		return False

	if doc.get("is_consolidated"):
		return True

	return any(item.get("pos_invoice") for item in doc.get("items", []))


def create_ingredient_consumption_entry(item_code, qty, warehouse, invoice_ref,
										 invoice_type, company=None, posting_date=None, posting_time=None, invoice_item=None):
	"""
	Create Stock Entry for consuming ingredients based on BOM.

	Args:
		item_code: Composite item code
		qty: Quantity of composite item sold
		warehouse: Warehouse to deduct from
		invoice_ref: Reference to invoice for tracking
		invoice_type: Type of invoice (POS Invoice or Sales Invoice)
		company: Company of the invoice being processed
		posting_date: Date of posting
		posting_time: Time of posting

	Returns:
		Stock Entry document
	"""
	if invoice_type not in ('Sales Invoice', 'POS Invoice') or not invoice_item:
		frappe.throw(_('Cần hóa đơn và mã dòng nguồn để xuất nguyên liệu.'))
	frappe.db.sql(f'SELECT name FROM `tab{invoice_type}` WHERE name=%s FOR UPDATE', invoice_ref)
	# Locking read tránh snapshot cũ khi request khác vừa hoàn tất.
	existing = frappe.db.sql('''SELECT name, custom_source_invoice_item FROM `tabStock Entry`
		WHERE custom_source_invoice=%s AND custom_invoice_type=%s
		AND custom_composite_item=%s AND docstatus=1 FOR UPDATE''',
		(invoice_ref, invoice_type, item_code), as_dict=True)
	if any(not row.custom_source_invoice_item for row in existing):
		frappe.throw(_('Phiếu xuất lịch sử chưa có mã dòng nguồn; cần đối soát trước khi chạy lại.'))
	existing = [row.name for row in existing if row.custom_source_invoice_item == invoice_item]
	if existing:
		return frappe.get_doc("Stock Entry", existing[0])

	# Handle returns (negative quantity)
	is_return = qty < 0
	abs_qty = abs(qty)

	# Get the recipe (BOM) — đúng company của hóa đơn đang xử lý
	bom = get_active_bom(item_code, company)
	if not bom:
		frappe.throw(_("No active recipe found for item {0}").format(item_code))
	
	# Get ingredients from BOM
	ingredients = get_bom_ingredients(bom, abs_qty)
	
	if not ingredients:
		frappe.throw(_("No ingredients found in recipe for {0}").format(item_code))
	
	# Create Stock Entry
	stock_entry = frappe.new_doc("Stock Entry")
	# TRƯỚC ĐÂY: luôn dùng company mặc định TOÀN CỤC của user hiện tại thay
	# vì company của CHÍNH hóa đơn — với 1 công ty duy nhất trên site hiện
	# tại thì luôn khớp nhau nên không lộ ra, nhưng ngay khi 1 property có
	# operating_company KHÁC company mặc định toàn cục (Property v2), Stock
	# Entry sẽ mang company SAI so với warehouse của nó (warehouse thuộc
	# company của hóa đơn) — ERPNext core sẽ từ chối lưu do company không
	# khớp warehouse, khiến MỌI hóa đơn có composite item ở property đó thất
	# bại ngay khi submit.
	stock_entry.company = company or frappe.defaults.get_defaults().get("company")
	
	if is_return:
		stock_entry.stock_entry_type = "Material Receipt"
		stock_entry.purpose = "Material Receipt"
	else:
		# Only validate availability if we are consuming
		validate_ingredient_availability(ingredients, warehouse, posting_date, posting_time)
		stock_entry.stock_entry_type = "Material Consumption for Manufacture"
		stock_entry.purpose = "Material Consumption for Manufacture"
	
	if posting_date:
		stock_entry.set_posting_time = 1
		stock_entry.posting_date = posting_date
	if posting_time:
		stock_entry.posting_time = posting_time
	
	# Add custom fields for tracking
	stock_entry.custom_composite_item = item_code
	stock_entry.custom_source_invoice = invoice_ref
	stock_entry.custom_invoice_type = invoice_type
	stock_entry.custom_source_invoice_item = invoice_item
	
	# Add ingredients as items
	for ingredient in ingredients:
		row = {
			"item_code": ingredient["item_code"],
			"qty": ingredient["qty"],
			"uom": ingredient["uom"],
			"stock_uom": ingredient["stock_uom"],
			"conversion_factor": ingredient.get("conversion_factor", 1)
		}
		
		if is_return:
			row["t_warehouse"] = warehouse
		else:
			row["s_warehouse"] = warehouse
			
		stock_entry.append("items", row)
	
	# Save and submit
	stock_entry.insert(ignore_permissions=True)
	stock_entry.submit()
	
	return stock_entry


def reverse_ingredient_consumption(invoice_doc, item):
	"""
	Reverse stock entry when invoice is cancelled.
	
	Args:
		invoice_doc: Invoice document
		item: Item row from invoice
	"""
	# Find the stock entry created for this invoice and item
	stock_entries = frappe.get_all(
		"Stock Entry",
		filters={
			"custom_source_invoice": invoice_doc.name,
			"custom_invoice_type": invoice_doc.doctype,
			"custom_composite_item": item.item_code,
			"docstatus": 1
		},
		pluck="name"
	)
	
	# Cancel all related stock entries. Re-raise (after logging) instead of
	# swallowing the error, so the caller's existing handler blocks the POS
	# Invoice cancellation the same way it already blocks a failed submit —
	# otherwise the invoice/folio charge gets reversed while the ingredient
	# stock silently stays consumed, with no visible error anywhere.
	for entry_name in stock_entries:
		try:
			stock_entry = frappe.get_doc("Stock Entry", entry_name)
			stock_entry.cancel()
		except Exception as e:
			frappe.log_error(
				message=f"Error cancelling stock entry {entry_name}: {str(e)}",
				title="Stock Entry Cancellation Error"
			)
			raise


def get_active_bom(item_code, company=None):
	"""
	Get the active BOM for a composite item, matching `company` when given.

	TRƯỚC ĐÂY: luôn trả về ĐÚNG 1 BOM (Item Recipe.bom hoặc default_bom),
	bất kể company nào đang xử lý hóa đơn — an toàn khi site chỉ có 1
	company, nhưng khi 2 property thuộc 2 company KHÁC NHAU cùng bán 1
	composite item, BOM mặc định (thuộc company A) bị dùng nhầm cho hóa đơn
	của company B — ERPNext sẽ từ chối Stock Entry vì company không khớp
	company của warehouse. BOM đã có sẵn field `company` (không cần thêm
	field mới) — tra trực tiếp theo (item, company); nếu company đó CHƯA có
	BOM riêng, tự tạo 1 bản sao từ đúng công thức nguyên liệu của Item
	Recipe (không tự bịa công thức khác).

	Args:
		item_code: Item code
		company: Company of the invoice being processed (None = hành vi cũ,
			dùng cho các nơi gọi không có ngữ cảnh company, VD
			get_available_to_make()).

	Returns:
		BOM name or None
	"""
	if company:
		existing = frappe.db.get_value(
			"BOM",
			filters={"item": item_code, "company": company, "is_active": 1, "docstatus": 1},
			fieldname="name",
			order_by="creation desc"
		)
		if existing:
			return existing

	# Try to get from Item Recipe first
	recipe = frappe.db.get_value("Item Recipe", item_code, "bom")
	if recipe:
		if not company:
			return recipe
		recipe_company = frappe.db.get_value("BOM", recipe, "company")
		if recipe_company == company:
			return recipe
		# BOM mặc định của Item Recipe thuộc CÔNG TY KHÁC — tự tạo bản sao
		# đúng company này từ cùng công thức nguyên liệu, thay vì dùng nhầm
		# BOM sai company (hoặc bỏ cuộc, chặn đứng cả hóa đơn).
		recipe_doc = frappe.get_doc("Item Recipe", item_code)
		return recipe_doc.create_bom(company=company)

	# Fallback to default BOM from Item
	bom = frappe.db.get_value("Item", item_code, "default_bom")
	if bom:
		if not company or frappe.db.get_value("BOM", bom, "company") == company:
			return bom

	# Find any active BOM for this item (matching company if given)
	bom_filters = {"item": item_code, "is_active": 1, "docstatus": 1}
	if company:
		bom_filters["company"] = company
	bom = frappe.db.get_value(
		"BOM",
		filters=bom_filters,
		fieldname="name",
		order_by="creation desc"
	)

	return bom


def get_bom_ingredients(bom_name, qty_multiplier):
	"""
	Get ingredients from BOM with quantities multiplied.
	
	Args:
		bom_name: BOM document name
		qty_multiplier: Quantity to multiply ingredient quantities by
		
	Returns:
		List of ingredient dicts
	"""
	bom = frappe.get_doc("BOM", bom_name)
	ingredients = []
	
	for item in bom.items:
		# Calculate required quantity based on BOM quantity
		qty_per_unit = flt(item.stock_qty) / flt(bom.quantity)
		required_qty = qty_per_unit * flt(qty_multiplier)
		
		ingredients.append({
			"item_code": item.item_code,
			"qty": required_qty,
			"uom": item.stock_uom,
			"stock_uom": item.stock_uom,
			"conversion_factor": 1
		})
	
	return ingredients


def validate_ingredient_availability(ingredients, warehouse, posting_date=None, posting_time=None):
	"""
	Validate that sufficient ingredients exist before sale.

	Args:
		ingredients: List of ingredient dicts
		warehouse: Warehouse to check
		posting_date/posting_time: thời điểm của hóa đơn đang xử lý — TRƯỚC
			ĐÂY không truyền, get_stock_balance() mặc định lấy tồn kho tại
			THỜI ĐIỂM HIỆN TẠI (nowdate()/nowtime()) bất kể hóa đơn ghi lùi
			ngày (posting_date trong quá khứ) hay không, có thể duyệt nhầm
			1 hóa đơn ghi lùi ngày dựa trên tồn kho SAU NÀY (đã được nhập
			thêm) thay vì tồn kho THẬT tại đúng thời điểm hóa đơn đó.

	Raises:
		frappe.ValidationError if insufficient stock
	"""
	insufficient_items = []

	for ingredient in ingredients:
		available_qty = get_available_qty(ingredient["item_code"], warehouse, posting_date, posting_time)
		
		if available_qty < ingredient["qty"]:
			insufficient_items.append({
				"item": ingredient["item_code"],
				"required": ingredient["qty"],
				"available": available_qty
			})
	
	if insufficient_items:
		error_msg = _("Insufficient ingredients to make this item:") + "\n"
		for item_info in insufficient_items:
			error_msg += _("• {0}: Required {1}, Available {2}").format(
				item_info["item"],
				item_info["required"],
				item_info["available"]
			) + "\n"
		
		frappe.throw(error_msg, title=_("Insufficient Stock"))


def get_available_qty(item_code, warehouse, posting_date=None, posting_time=None):
	"""
	Get available quantity of an item in warehouse.

	Args:
		item_code: Item code
		warehouse: Warehouse name
		posting_date/posting_time: nếu bỏ trống, get_stock_balance() mặc
			định lấy tồn kho tại THỜI ĐIỂM HIỆN TẠI — chỉ truyền khi cần
			tồn kho đúng tại 1 thời điểm cụ thể trong quá khứ (hóa đơn ghi
			lùi ngày), KHÔNG truyền cho các mục đích kiểm tra "còn bao
			nhiêu NGAY BÂY GIỜ" (VD get_available_to_make()).

	Returns:
		Float: Available quantity
	"""
	from erpnext.stock.utils import get_stock_balance

	return get_stock_balance(item_code, warehouse, posting_date, posting_time)


@frappe.whitelist()
def get_available_to_make(item_code, warehouse=None):
	"""
	Calculate how many units of composite item can be made
	based on available ingredients.
	
	Args:
		item_code: Composite item code
		warehouse: Optional warehouse filter
		
	Returns:
		Dict with quantity and details
	"""
	if not frappe.has_permission("Item", "read", doc=item_code):
		frappe.throw(_("Không có quyền xem thông tin Item {0}.").format(item_code), frappe.PermissionError)

	# Check if item is composite
	is_composite = frappe.db.get_value("Item", item_code, "is_composite_item")
	if not is_composite:
		return {"qty": 0, "message": "Item is not a composite item"}
	
	# Get BOM
	bom_name = get_active_bom(item_code)
	if not bom_name:
		return {"qty": 0, "message": "No active recipe found"}
	
	bom = frappe.get_doc("BOM", bom_name)
	
	# Calculate maximum quantity based on ingredients
	max_qty = None
	ingredient_details = []
	
	for item in bom.items:
		qty_per_unit = flt(item.stock_qty) / flt(bom.quantity)
		available = get_available_qty(item.item_code, warehouse)
		
		# Calculate how many units can be made with this ingredient
		if qty_per_unit > 0:
			can_make = available / qty_per_unit
		else:
			can_make = 0
		
		ingredient_details.append({
			"ingredient": item.item_code,
			"required_per_unit": qty_per_unit,
			"available": available,
			"can_make": int(can_make)
		})
		
		# Track the limiting ingredient
		if max_qty is None or can_make < max_qty:
			max_qty = can_make
	
	return {
		"qty": int(max_qty) if max_qty is not None else 0,
		"ingredients": ingredient_details,
		"message": "Success"
	}
